url: "roquec.com"

collections_dir: content

collections:
  articles:
    output: true
    permalink: /:collection/:name
  drawings:
    output: true
    permalink: /:collection/:name
  projects:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: "content/*"
    values:
      layout: "article"
      author: "RoqueC"
  - scope:
      path: ""
    values:
      layout: "base"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
