url: "https://roquec.com"

includes_dir: .

collections_dir: content

collections:
  articles:
    output: true
  drawings:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "content/*"
    values:
      layout: "article"
      author: "RoqueC"
      feature_index: 999
  - scope:
      path: ""
    values:
      layout: "base"
      type: "md"
      icon: "markdown"

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
