url: "roquec.com"

collections_dir: content

collections:
  articles:
    output: true
  drawings:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "content/*"
    values:
      layout: "article"
      author: "RoqueC"
  - scope:
      path: ""
    values:
      layout: "base"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
