url: "https://roquec.com"

layouts_dir: ./_html
includes_dir: .

collections_dir: content

collections:
  articles:
    output: true
  drawings:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "content/*"
    values:
      layout: "layouts/article"
      author: "RoqueC"
      feature_index: 999
  - scope:
      path: ""
    values:
      layout: "base"
      type: "md"
      icon: "markdown"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

obfuscated_email: "&#x72;&#x6f;&#x71;&#x75;&#x65;&#x63;&#x61;&#x72;&#x72;&#x69;&#x7a;&#x6f;&#x66;&#x40;&#x67;&#x6d;&#x61;&#x69;&#x6c;&#x2e;&#x63;&#x6f;&#x6d;"
obfuscated_mailto: "&#x6d;&#x61;&#x69;&#x6c;&#x74;&#x6f;&#x3a;&#x72;&#x6f;&#x71;&#x75;&#x65;&#x63;&#x61;&#x72;&#x72;&#x69;&#x7a;&#x6f;&#x66;&#x40;&#x67;&#x6d;&#x61;&#x69;&#x6c;&#x2e;&#x63;&#x6f;&#x6d;"
