url: "https://roquec.com"
author: "Roque Carrizo"
description: "Roque's very own personal portfolio website!"

layouts_dir: ./_html
includes_dir: .

collections_dir: content

collections:
  articles:
    output: true
  drawings:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: "content/*"
    values:
      layout: "layouts/article"
  - scope:
      path: ""
    values:
      layout: "base"
      type: "md"
      icon: "markdown"

plugins:
  - jekyll-sitemap

obfuscated_email: "&#99;&#x6f;&#110;&#116;&#97;&#99;&#116;&#64;&#114;&#x6f;&#x71;&#117;&#x65;&#99;&#x2e;&#99;&#x6f;&#109;"
obfuscated_mailto: "&#x6d;&#97;&#x69;&#x6c;&#116;&#111;&#x3a;&#99;&#x6f;&#110;&#116;&#97;&#99;&#116;&#64;&#114;&#x6f;&#x71;&#117;&#x65;&#99;&#x2e;&#99;&#x6f;&#109;"
