name: CI/CD
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version data
        shell: pwsh
        run: .\.github\util\set-version.ps1
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Build Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./src"
      - name: Run Lighthouse CI
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.github/util/lighthouserc.json'
          temporaryPublicStorage: true
      - name: Lighthouse report
        shell: pwsh
        env:
          LIGHTHOUSE_MANIFEST: ${{steps.lighthouse.outputs.manifest}}
          LIGHTHOUSE_LINKS: ${{steps.lighthouse.outputs.links}}
        run: .\.github\util\print-lighthouse-report.ps1
      - uses: actions/upload-artifact@v3
        with:
          name: lighthouse
          path: gist
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  gist:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: lighthouse
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GISTS_ACCESS_TOKEN }}
          gist_id: 3f8ee5d85053832ea374a05b301f57aa
          file_path: performance.json
