name: CI/CD
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version data
        shell: pwsh
        run: .\.github\util\set-version.ps1
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Build Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./src"
      - name: Run Lighthouse CI
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.github/util/lighthouserc.json'
          temporaryPublicStorage: true
      - name: Print Lighthouse report
        shell: pwsh
        env:
          LIGHTHOUSE_MANIFEST: ${{steps.lighthouse.outputs.manifest}}
          LIGHTHOUSE_LINKS: ${{steps.lighthouse.outputs.links}}
        run: .\.github\util\print-lighthouse-report.ps1
      - name: Update Lighthouse JSON
        run: |
          git config user.name 'Portfolio GitHub Actions'
          git config user.email '<>'
          git clone https://gist.github.com/3f8ee5d85053832ea374a05b301f57aa.git gist
          '{"performance":${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.performance }},"accessibility":${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.accessibility  }},"bestPractices":${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.best-practices }},"seo":${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.seo }}}' > .\gist\roquec-lighthouse.json
          git -C .\gist add .
          git -C .\gist commit -m "update data"
          git -C .\gist push
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: foo-user/bar-repo
          path: './gist'
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
