name: CI/CD
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version data
        shell: pwsh
        run: .\.github\actions\set-version.ps1
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Build Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: "./src"
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v2
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  lighthouse:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Download action scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: '.github/actions'
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x
      - name: Run Lighthouse
        run: |
          lhci autorun --collect.numberOfRuns=5 --collect.url=https://roquec.com/main${{github.run_id}} --upload.target=filesystem --upload.outputDir=./reports/mobile
          lhci autorun --collect.numberOfRuns=5 --collect.url=https://roquec.com/main${{github.run_id}} --upload.target=filesystem --upload.outputDir=./reports/desktop --collect.settings.preset=desktop
      - name: Generate report
        shell: pwsh
        run: .\.github\actions\lighthouse-report.ps1
        env:
          LIGHTHOUSE_PATH_MOBILE: ./reports/mobile
          LIGHTHOUSE_PATH_DESKTOP: ./reports/desktop
          LIGHTHOUSE_REPORT_OUTPUT_DIR: ./summary
      - name: Publish to Gist
        shell: pwsh
        env:
          UPDATE_GIST_TOKEN: ${{ secrets.GISTS_ACCESS_TOKEN }}
          UPDATE_GIST_ID: 3f8ee5d85053832ea374a05b301f57aa
          UPDATE_GIST_PATH: summary
        run: .\.github\actions\update-gist.ps1
